import { useState } from 'react';
import Head from 'next/head';
import { Inter } from '@next/font/google';
import RichTextEditor from '../components/RichTextEditor';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [value, setValue] = useState('');

  return (
    <>
      <Head>
        <title>WYSIWYG</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={inter.className}>
        <section>
          <div>
            <RichTextEditor setValue={setValue} />
          </div>
          <div>
            <h1>Result</h1>
            <p>{value}</p>
          </div>
        </section>
      </main>
    </>
  );
}
